# -*- coding: utf-8 -*-
"""diploma-research.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-4Sgsh64lq-Dn_F_MZVl-zJR9qDsjSK
"""

from datetime import datetime

protection = datetime(2023, 6, 9)
today = datetime.now()

print(f'До защиты {protection - today}')

"""**ГРАФИК РАССЕНИЯ**"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/hamzreg/bmstu-diploma/main/src/scripts/stat/vm2/stat.csv')

df.plot.scatter(x = 'ENTROPY', y = 'COMPRESSION_RATIO', s = 5);
df.plot.scatter(x = 'ENTROPY', y = 'SPACE_SAVINGS', s = 5, c = 'g');
df.plot.scatter(x = 'ENTROPY', y = 'COMPRESSION_FACTOR', s = 5, c = 'r');
df.plot.scatter(x = 'ENTROPY', y = 'COMPRESSION_GAIN', s = 5, c = 'y');